<!DOCTYPE html>
<!-- Generated by PHPWord -->
<html>
<head>
	<meta charset="UTF-8" />
	<title>PHPWord</title>
	<style>
		* {font-family: Arial; font-size: 10pt;}
		a.NoteRef {text-decoration: none;}
		hr {height: 1px; padding: 0; margin: 1em 0; border: 0; border-top: 1px solid #CCC;}
		table {border: 1px solid black; border-spacing: 0px; width : 100%;}
		td {border: 1px solid black;}
		.oneUserDefinedStyle {font-family: 'Tahoma'; font-size: 10pt; color: #1B2232; font-weight: bold;}
		.T1 {}
		.T2 {font-family: 'Tahoma'; font-size: 10pt;}
		.P1 {margin-top: 0; margin-bottom: 0;}
		.T3 {font-family: 'Tahoma'; font-size: 13pt; font-weight: bold;}
	</style>
</head>
<body>
	<p style="margin-top: 0; margin-bottom: 0; text-align: center;"><span class="T3">RT 04 RW 05</span></p>
	<p style="margin-top: 0; margin-bottom: 0; text-align: center;"><span class="">Kelurahan Lenteng Agung Kecamatan Jagakarsa Kota Jakarta Selatan</span></p>
	<hr>
	<font face="Arial" color="black" size="6"> <p align="center"> <u> <b> SURAT KETERANGAN PENGANTAR </b></u></p> 
		@foreach ($cetak as $q)
		<p face="Arial" color="black" size="4" align="center"> Nomor: {{$q->nomor_pengantar}}/2020 </p>
		@endforeach
	</font>
	<p>Yang bertanda tangan dibawah ini :</p>
	@foreach ($cetak as $q)
	<p>Nama : {{$q->nama}} <br>
		Jabatan : -<br> 
	</p>
	@endforeach

	<p>Menerangkan dengan sesungguhnya bahwa : </p>
	@foreach ($cetak as $p)
	<p>
		Nama : {{$p->nama}} <br>
		Nik :  {{$p->nik}}<br>
		Nomor Pengantar : {{$p->nomor_pengantar}} <br>
		Tanggal Berlaku : {{$p->tanggal_berlaku}} <br>
		Tanggal Pengantar : {{$p->tanggal_pengantar}} <br>
		Keperluan  : {{$p->keperluan}}<br>
		Lain lain : {{$p->lain_lain}}</p>
		@endforeach

		<p>Demikian surat keterangan ini dibuat untuk digunakan seperlunya</p>
		<p align="right">Dibuat di : Depok</p>
		@foreach ($cetak as $es)
		<p align="right">Pada tanggal : {{$es->tanggal_berlaku}}</p>
		@endforeach
		<div align="center">
			<span style="font-size: x-small;">Mengetahui</span></div>
			<div align="left">
				<span style="font-size: x-small;">Tanda Tangan Pemegang</span></div>

				<div align="right">
					<span style="font-size: x-small;">Ketua RT</span></div>
				</div>

			</body>
			</html>