<!DOCTYPE html>
<!-- Generated by PHPWord -->
<html>
<head>
	<meta charset="UTF-8" />
	<title>PHPWord</title>
	<style>
		* {font-family: Arial; font-size: 10pt;}
		a.NoteRef {text-decoration: none;}
		hr {height: 1px; padding: 0; margin: 1em 0; border: 0; border-top: 1px solid #CCC;}
		table {border: 1px solid black; border-spacing: 0px; width : 100%;}
		td {border: 1px solid black;}
		.oneUserDefinedStyle {font-family: 'Tahoma'; font-size: 10pt; color: #1B2232; font-weight: bold;}
		.T1 {}
		.T2 {font-family: 'Tahoma'; font-size: 10pt;}
		.P1 {margin-top: 0; margin-bottom: 0;}
		.T3 {font-family: 'Tahoma'; font-size: 13pt; font-weight: bold;}
	</style>
</head>
<body>
	<p style="margin-top: 0; margin-bottom: 0; text-align: center;"><span class="T3">RT 04 RW 05</span></p>
	<p style="margin-top: 0; margin-bottom: 0; text-align: center;"><span class="">Kelurahan Lenteng Agung Kecamatan Jagakarsa Kota Jakarta Selatan</span></p>
	<hr>
	<font face="Arial" color="black" size="6"> <p align="center"> <u> <b> SURAT KETERANGAN PENGANTAR </b></u></p> <p face="Arial" color="black" size="4" align="center"> Nomer: /2020 </p></font>
	<p>Yang bertanda tangan dibawah ini :</p>
	<p>Nama : <br>
		Jabatan : <br>
	Alamat : </p>
	<p>Menerangkan dengan sesungguhnya bahwa : </p>
	<p>
		Nama : <br>
		Nik : <br>
		Nomor Pengantar <br>
		Keperluan <br>
	Lain lain : </p>
	<p>Demikian surat keterangan ini dibuat untuk digunakan seperlunya</p>
	<p align="right">Dibuat di : Depok</p>
	<p align="right">Pada tanggal : </p>
	<div align="center">
		<span style="font-size: x-small;">Mengetahui</span></div>
		<div align="left">
			<span style="font-size: x-small;">Tanda Tangan Pemegang</span></div>
			<div align="right">
				<span style="font-size: x-small;">Ketua RT</span></div>
			</div>

		</body>
		</html>
